### ISSUE TITLE
Psych::SyntaxError

### ISSUE THREAD

**Issue by pioz** [feedbackmine/language_detector#4]
With ruby 2.0.0-p247 I've the follow error:

```
2.0.0p247 :001 > require 'language_detector'
 => true 
2.0.0p247 :002 > d = LanguageDetector.new
Psych::SyntaxError: (/Users/pioz/.rvm/gems/ruby-2.0.0-p247/gems/language_detector-0.1.0/lib/model-tc.yml): did not find expected key while parsing a block mapping at line 5 column 5
    from /Users/pioz/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/psych.rb:205:in `parse'
    from /Users/pioz/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
    from /Users/pioz/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/psych.rb:153:in `parse'
    from /Users/pioz/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/psych.rb:129:in `load'
    from /Users/pioz/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/psych.rb:299:in `block in load_file'
    from /Users/pioz/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/psych.rb:299:in `open'
    from /Users/pioz/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/psych.rb:299:in `load_file'
    from /Users/pioz/.rvm/gems/ruby-2.0.0-p247/gems/language_detector-0.1.0/lib/language_detector.rb:141:in `load_model'
    from /Users/pioz/.rvm/gems/ruby-2.0.0-p247/gems/language_detector-0.1.0/lib/language_detector.rb:14:in `initialize'
    from (irb):2:in `new'
    from (irb):2
    from /Users/pioz/.rvm/rubies/ruby-2.0.0-p247/bin/irb:12:in `<main>'
2.0.0p247 :003 > 
```

**Comment by mtmail** [comment]
(work-around)
It's fixed in the repository already. You'd need to overwrite the _language_detect.rb_ with the one from _https://raw.github.com/feedbackmine/language_detector/master/lib/language_detector.rb_
